# Generated by Django 3.1.1 on 2020-10-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
